name: Tests

on: 
    push: 
        branches: 
            - main
            - "apps/*"
            - develop
    pull_request: 
        branches: 
            - main

jobs:
    test_cases:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Use Node.js 
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Installing dependencies
              run: npm install 

            - name: Run tests
              run: npm test
